title: "Aufgabenerstellung mit Quarto und Export nach QTI 3.0 für ILIAS"
subtitle: "Konzeption und prototypische Implementierung einer Erweiterung"
author: "Manuel Koell"
email: "mko7395@students.fhv.at"
advisor: "Mag. Dr. Peter REITER, Bakk."
location: "Dornbirn"
date: today
date-format: "MMMM YYYY"
lang: de
bibliography: assets/references.bib
csl: assets/ieee.csl
