title: "Aufgabenerstellung mit Quarto und Export nach QTI 3.0 für ILIAS"
subtitle: "Konzeption und prototypische Implementierung einer Erweiterung"
author: "Manuel Koell"
email: "mko7395@students.fhv.at"
advisor: "Mag. Dr. Peter REITER, Bakk."
location: "Dornbirn"
date: today
date-format: "MMMM YYYY"
lang: de

project:
  type: book
  output-dir: docs
  post-render: 
    - bash -c "rm pdfa.xmpi"

format:
  pdf:
    template: templates/titlepage.tex
    latex-auto-install: true
    pdf-engine: pdflatex
    # keep-tex: true

bibliography: assets/references.bib
csl: assets/ieee.csl
