date: "2027-07-07"
project:
  type: book
  output-dir: docs

book:
  output-file: "bachelorarbeit_mko7395"
  chapters:
    - index.qmd
    - thesis/01-einleitung.qmd
    - thesis/02-stand-der-technik.qmd
    - thesis/03-aufgabenstellung.qmd
    - thesis/04-methodik.qmd
    - thesis/05-umsetzung.qmd
    - appendix.qmd

format:
  pdf:
    template: templates/titlepage.tex
    latex-auto-install: true
    # keep-tex: true